DEFAULT_HOST = "localhost"
DEFAULT_PORT = 8888
ENDPOINT_GET_CHAINSPEC = "chainspec"
ENDPOINT_GET_METRICS = "metrics"
ENDPOINT_GET_STATUS = "status"
ENDPOINT_GET_VALIDATOR_CHANGES = "validator-changes"
